repos:
  # https://github.com/astral-sh/ruff-pre-commit
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.2
    hooks:
      # Run the linter.
      - id: ruff-check
        files: \.py$
        args: [ --fix, --show-fixes ]
      # Run the formatter.
        files: \.py$
      - id: ruff-format
